# Generated by Django 2.2.17 on 2020-12-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_authlib_oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
