# Generated by Django 3.2 on 2021-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_authlib_oauth2', '0002_add_client_logo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='nonce',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
