# Generated by Django 3.2 on 2021-04-23 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_authlib_oauth2.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_authlib_oauth2', '0003_add_authorizationcode_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField(default='')),
                ('given_at', models.IntegerField(default=django_authlib_oauth2.models.now_timestamp)),
                ('expires_in', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_authlib_oauth2.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'client')},
            },
        ),
    ]
