# Generated by Django 3.2 on 2021-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_authlib_oauth2', '0004_add_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
